#!/bin/sh
# echo "Linker args: $@" >> /dev/pts/4

# Ensure `lmips` binary exists, and mipsel chroot is ready.
make lmips .mipsel

# Run `lmips` binary with required permissions
# and pass through linker arguments.
sudo ./lmips $@
